#!/bin/sh

# fdisk -lu <image>, extract start of partition, and note blocksize (512)
# losetup /dev/loop0 <image> --offset $(( start * blocksize))
# mount /dev/loop0 /mnt

ssh-keygen -t 'rsa' -f ssh_host_rsa_key
ssh-keygen -t 'dsa' -f ssh_host_dsa_key
ssh-keygen -t 'ecdsa' -f ssh_host_ecdsa_key
ssh-keygen -t 'ed25519' -f ssh_host_ed25519_key

